### ISSUE TITLE
Is there a way i can authenticate tacacs+ using this module.?

### ISSUE THREAD

**Issue by sudhirbitsgoa** [santsys/node-tacacs-plus#1]

**Comment by santsys** [comment]
You can perform an authentication, but it's not a native function. You would have to build and decode each package of information that is required. If you look in the readme there is a basic outline of starting an authentication (https://github.com/santsys/node-tacacs-plus#creating-a-simple-auth-start). There are also a few code samples in there that should get you started depending on what you're looking to do.
