### ISSUE TITLE
Few questions on tacacs plus package implementation

### ISSUE THREAD

**Issue by nareshbandameedi** [santsys/node-tacacs-plus#2]
I want to use tacacs-plus package in my project to implement user authentication and authorization process. So, I need few clarifications on the usage of this package.
1. How the tacacs-plus server (simple server.js file ) validates the user?
2. Where can we store the user details(like username, password)?
3. In the tacacs-plus server (as given example in package) file takes the username in the first request and ask for a password in the reply. So, How can we implement user validation against stored user data?
4. Is this 
https://networkjutsu.com/tacacs-ubuntu/ or
http://www.routingloops.co.uk/cisco/tacacs-on-ubuntu-14-04-lts/
the right(approachable) way to setup tacacs-plus server in unix and provide a IP address of the machine in tacacs-plus server.js file?
5. How to implement user login and change password and update user details using tacacs-plus package?

**Comment by santsys** [comment]
This code is only a wrapper for the underlying protocol, not an authentication implementation that uses the protocol. So this package can help you accomplish the tasks listed, but, you would have to figure out the details of user/password security, validation, storage, etc. 

This is only a protocol implementation, not a complete authentication system.
