### ISSUE TITLE
Null shared secret allows brute force to succeed

### ISSUE THREAD

**Issue by mwarner1** [santsys/node-tacacs-plus#4]
I noticed during testing that if the shared_secret in the sample usage code is null that the code will eventually erroneously return TAC_PLUS_AUTHEN_STATUS_PASS when being called concurrently. I've put together sample code that illustrates this:
 
https://gist.github.com/mwarner1/4e6c9a06638302328e54aa7aca1c5477

**Comment by mwarner1** [comment]
The resp object for the case where the code erroneously gets TAC_PLUS_AUTHEN_STATUS_PASS has nonsensical data in the data.message field (see below).

DEBUG response { header: 
   { majorVersion: 12,
     minorVersion: 0,
     versionByte: 192,
     type: 1,
     sequenceNumber: 2,
     flags: 4,
     is_encrypted: true,
     is_singleConnect: true,
     sessionId: 173459152,
     length: 33 },
  rawData: <Buffer a1 d5 cc 73 ad 0c 2b 66 a9 e7 a7 08 58 07 0a ad af 54 e5 e6 f1 dd 30 13 81 1a 45 20 85 4f 5a 48 31>,
  data: 
   { status: 1,
     flags: 5,
     message: '+f)g\'\bX\u0007\n-/Tefq]0\u0013\u0001\u001aE \u0005OZH1',
     data: '' } }

**Comment by mwarner1** [comment]
A very kludgey workaround is to additionally check the flags and the header length. I've only tested this with tac_plus. I haven't figured out how to interpret the response from tac_plus with a bad shared key.

```
else if (resp.data.status === tacacs.TAC_PLUS_AUTHEN_STATUS_PASS && resp.data.flags === 0 && resp.header.length !== 33) {
                            console.log("DEBUG response", resp);
                            console.log("DEBUG rawData", resp.rawData.toString('UTF-8'));
                            console.log("Header info", resp.data.flags, resp.data.status);
                            client.end();
                            authMessage = "Success";
                            authResult = AuthResult.Success;
```

**Comment by santsys** [comment]
Hey, thanks for the report. 

I'll take a look through the spec and see if I can find any specifics that outline the case you mention and or add in some checks around it.

**Comment by santsys** [comment]
With a bad shared key (or one not set) with encryption enabled, the spec does identify that the server should return Error in those cases.

> When a server detects that the secret(s) it has configured for the device mismatch, it MUST return ERROR. The handling of the TCP connection by the server is implementation independent.

So it seems like your server is returning some invalid data that is being decoded incorrectly and or some data is being mishandled. 

Now why that is for some reason sending a pass status in the header, that I am unsure of... If you have a pcap of the communications that may prove to be more helpful than anything.

**Comment by mwarner1** [comment]
The TCP dump shows an encrypted data stream coming back from tac_plus. From before, it looks like it's just garbage when it's decrypted. Weird! PCAP attached.
[dump.zip](https://github.com/santsys/node-tacacs-plus/files/2882542/dump.zip)

**Comment by santsys** [comment]
The failed decryption would be expected if encryption is set but no key is configured on the client (e.g. the server is responding with encrypted content, but the client doesn't know what to do with it).

Looks like in the authentication flow we need to do some checking to validate the decryption success. 

Specifically:
>After a packet body is decrypted, the lengths of the component values in the packet are summed. If the sum is not identical to the cleartext datalength value from the header, the packet MUST be discarded, and an error signalled. The underlying TCP connection MAY also be closed, if it is not being used for other sessions in single-connect mode.

**Comment by mwarner1** [comment]
Yes, I believe it would be useful to know explicitly that the decryption process failed.

Separately, I tried this against a Cisco ISE instance and, interestingly, an incorrect shared secret causes the client to hang. A packet capture shows ISE acknowledges the authentication packet but nothing after that until the client finally times out (20 seconds in my case). Packet capture attached, if you're interested.
[dump.zip](https://github.com/santsys/node-tacacs-plus/files/2885459/dump.zip)

**Comment by mwarner1** [comment]
BTW, I also see the garbled message when the shared key is bad (not just when it's missing).

**Comment by mwarner1** [comment]
I almost forgot to thank you for writing this code. It has been very helpful!

**Comment by santsys** [comment]
I'm almost done with modifications that validate the data in the authentication process and will throw an exception with the message "Data length mismatch. If using encryption please verify your keys are correct."

The reason you got an pass value at some point was basically because of failed decryptions that eventually put a "good" value in the data. I'm also making some updates to some of the examples and cleaning up some code as well as adding in some method jsdoc details. I'll push up a 1.2.1 version sometime today to resolve the issues.

Thank you!

**Comment by mwarner1** [comment]
Sounds good. Thanks!

**Comment by santsys** [comment]
Pushed up a v1.2.1 that should hopefully correct the issues you are seeing. Thank you.

**Comment by mwarner1** [comment]
Just tested and it's working as expected (throws an error with a bad or missing shared key). Thanks again!
