### ISSUE TITLE
CHAP authentication service

### ISSUE THREAD

**Issue by sudhirbitsgoa** [santsys/node-tacacs-plus#6]
The chap authentication says that there is three way handshake.
The password is hashed 

Does this module take care of handshake and hashing when CHAP authentication service is selected.

**Comment by santsys** [comment]
This code does not currently handle any CHAP authentication specific processes. You should be able to use this code to pass CHAP authentications back and forth (the handshake process), but it doesn't have any special handling currently implemented.  If there is something specific you're looking for, please outline it and we can bump it as a feature request.

**Comment by 50rayn** [comment]
Hello @sudhirbitsgoa ,
As far as I know, this module doesn't support this type of encryption and I don't see it to be maintained. 
Please consider this instead [@noction/tacacs-plus](https://github.com/Noction/tacacs-plus). 😊
